import glob as gb
import os
import warnings
import streamlit as st
import pandas as pd
import xlwings as xw # Xlwings is a Python library that makes it easy to call Python from Excel
# used to filter out warning messages generated by modules or functions called in code.
warnings.filterwarnings("ignore")

# function get LVH report based on specific criteria
def get_LVH_report(name):
    try:
        # Open the file named 'name' and read its contents
        with open(name, "r", encoding="cp1252", errors="ignore") as f:
            # Read all lines from the file and store them in a list named flist
            flist = f.readlines()
            
            # Initialize an empty list to store line numbers where 'LV-D' occurs
            lvh_count = [] 
            # Iterate through each line in flist along with its line number
            for num, line in enumerate(flist, 0):
                # If 'LV-D' is in the line, append its line number to lvh_count list
                if 'LV-H' in line:
                    lvh_count.append(num)
                # If 'LV-E' is in the line, store its line number as numend
                if 'LV-I' in line:
                    numend = num
            # Store the line number of the first occurrence of 'LV-B'
            numstart = lvh_count[0] 
             # Slice flist from the start of 'LV-D' to the line before 'LV-E' and store it in lvh_rpt
            lvh_rpt = flist[numstart:numend]
            
            # create two lists lvh_str and space to store lines between LV-D and LV-E 
            lvh_str = []
            space = [] # space list to store space type
            # iterate in each line of lvh_rpt
            for line in lvh_rpt:
                # condition for each line to get the specific rows
                if ('.' in line and 'RUN' not in line):
                    lvh_str.append(line)
                # condition to store line which contains 'in space'
                elif ('in space:' in line):
                    space.append(line)
            
            # result list to store filtered columns. after 7th column from last remaining values in 1 column. 
            result = []  
            for line in lvh_str:
                lvh_list = []
                # Split the line by whitespace and store the result in splitter
                splitter = line.split()
                 # Join the first part of the splitter except the last 7 elements and store it as space_name
                space_name = " ".join(splitter[:-10])
                # Add space_name as the first element of lvh_list
                lvh_list=splitter[-10:]
                lvh_list.insert(0,space_name)
                # Append lvh_list to result
                result.append(lvh_list)
            
            # stores result list to dataframe as lvh_df
            lvh_df = pd.DataFrame(result) 
            # select last 10 columns
            last10 = lvh_df.iloc[:, -10:]
            # convert to numeric (strings -> NaN)
            last10_numeric = last10.apply(pd.to_numeric, errors='coerce')
            # keep rows where all last 10 columns are numeric
            lvh_df = lvh_df[last10_numeric.notna().all(axis=1)]
            # Allot lvh_df columns from sim file
            lvh_df.columns = ['Window Name', 'Multiplier', 'Glass Area(SQFT)', 'Glass Height(FT)', 'Glass Width(FT)',
                                'X(FT)', ' Y(FT)', 'Frame Area(SQFT)', 'Curbe Area(SQFT)', 'Frame U-Value(BTU/HR-SQFT-F)', 'Curbe U-Value(BTU/HR-SQFT-F)']
            # st.write(lvh_df)
        return lvh_df
    except Exception as e:
        print(f"An error occurred: {e}")
        columns = ['Window Name', 'Multiplier', 'Glass Area(SQFT)', 'Glass Height(FT)', 'Glass Width(FT)',
                                'X(FT)', ' Y(FT)', 'Frame Area(SQFT)', 'Curbe Area(SQFT)', 'Frame U-Value(BTU/HR-SQFT-F)', 'Curbe U-Value(BTU/HR-SQFT-F)']
        return pd.DataFrame(columns=columns)
